# Generated by Django 5.0.6 on 2024-09-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Username', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=10)),
                ('message', models.CharField(default='', max_length=13)),
            ],
        ),
    ]
